name: Discord Notification on Issue Creation

on:
  issues:
    types: [labeled]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    if: contains(github.event.label.name, 'bug') || contains(github.event.label.name, 'feature')

    steps:
      - name: Fetch Issue Details
        id: get_issue_details
        run: |
          API_RESPONSE=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }})
          echo "API Response: $API_RESPONSE"
          ISSUE_URL=$(echo "$API_RESPONSE" | jq -r '.html_url')
          ISSUE_TITLE=$(echo "$API_RESPONSE" | jq -r '.title')
          REPO_NAME="${{ github.repository }}"
          echo "issue_url=$ISSUE_URL" >> $GITHUB_ENV
          echo "issue_title=$ISSUE_TITLE" >> $GITHUB_ENV
          echo "repo_name=$REPO_NAME" >> $GITHUB_ENV

      - name: Send Discord Github Issues
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_GITHUB_ISSUES_WEBHOOK }}
          ISSUE_URL: ${{ env.issue_url }}
          ISSUE_TITLE: ${{ env.issue_title }}
          REPO_NAME: ${{ env.repo_name }}
        run: |
          SUBTITLE="**New Issue:** $ISSUE_TITLE **Repository:** $REPO_NAME"
          PAYLOAD=$(jq -n --arg url "<$ISSUE_URL>" --arg st "$SUBTITLE" '{content: ($st + "\n**More:** " + $url)}')
          curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" $DISCORD_WEBHOOK
